#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
    Computes active users over a specified time period
"""
__author__ = "ryan faulkner"
__date__ = "11/06/2012"
__license__ = "GPL (version 2 or later)"

import sys
import e3_settings as s
sys.path.append(s.__E3_Analysis_Home__)

import logging
import datetime
import argparse
import src.metrics.bytes_added as ba

# CONFIGURE THE LOGGER
logging.basicConfig(level=logging.DEBUG, stream=sys.stderr, format='%(asctime)s %(levelname)-8s %(message)s', datefmt='%b-%d %H:%M:%S')

EDIT_COUNT_IDX = 5

def main(args):

    logging.info(args)
    logging.info('Processing contribution volume metrics for daily users from %s to %s ... ' %
                 (args.date_start, args.date_end))

    with open(s.__data_home__ + args.output_file,'w') as file_obj:
        try:
            file_obj.write("\t".join(ba.BytesAdded.header()) + '\n')
        except IOError:
            logging.error('Could not write to file "%s":.' % args.output_file)
            return

        for row in ba.BytesAdded(date_start=args.date_start, date_end=args.date_end).process(
            log_progress=True,log_frequency=args.log_frequency, num_threads=args.num_threads).__iter__():
            try:
                if row[EDIT_COUNT_IDX] >= args.min_edit:
                    file_obj.write("\t".join([str(e) for e in row]) + '\n')
            except IndexError:
                logging.error("Could not write row %s." % str(row))
            except IOError:
                logging.error('Could not write to file "%s":.' % args.output_file)
                return

if __name__ == "__main__":

    # Initialize query date constraints
    today = datetime.datetime.now()
    yesterday = today - datetime.timedelta(days=1)

    today = "".join([today.strftime('%Y%m%d'), "000000"])
    yesterday = "".join([yesterday.strftime('%Y%m%d'),"000000"])
    out_filename = 'dau_out_' + yesterday[:8] + '-' + today[:8] + '.tsv'

    parser = argparse.ArgumentParser(
        description="This script computes generates a tsv conataning rev counts for dailiy active users.",
        epilog="",
        conflict_handler="resolve",
        usage = "./daily_active_users [-n NUMTHREADS] [-m MINEDIT] [-l LOGFREQUENCY] [-s DATE_START] " \
                "[-e DATE_END] [-o OUTFILE]"
    )

    parser.add_argument('-m', '--min_edit',type=int, help='minimum amounts of edits.',default=0)
    parser.add_argument('-s', '--date_start',type=str, help='Start date of measurement.',
        default=yesterday)
    parser.add_argument('-e', '--date_end',type=str, help='End date of measurement.', default=today)
    parser.add_argument('-l', '--log_frequency',type=int,help='How often to log progress.',default=0)
    parser.add_argument('-o', '--output_file',type=str,help='File to store output.',default=out_filename)
    parser.add_argument('-n', '--num_threads',type=int,help='Number of sub-processes.',default=1)
    args = parser.parse_args()

    sys.exit(main(args))